# Generated by Django 5.1.2 on 2024-12-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item',
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(to='item.item'),
        ),
    ]
