# Generated by Django 5.1.2 on 2025-01-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_category_order_alter_item_mg'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_orderd',
            field=models.BooleanField(default=False),
        ),
    ]
