# Generated by Django 5.1.2 on 2025-01-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='mobile',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
