# Generated by Django 5.1.2 on 2025-01-03 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_order_address_order_contact_no_order_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='order',
            name='district',
        ),
        migrations.RemoveField(
            model_name='order',
            name='division',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='upazila',
        ),
    ]
